# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

def common_pods

	#UI
	pod 'SteviaLayout', '~> 4.7.3'

	# Reactive
	pod 'RxSwift', '~> 5.1.1'
    	pod 'RxCocoa', '~> 5.1.1'
	pod 'Action', '~> 4.0'

	# Resources
    	pod 'R.swift', '~> 5.3.0'

	# Network
	pod 'Alamofire', '~> 4.9.1'
end

target 'Repo' do
  use_frameworks!
	common_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if Gem::Version.new('11.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
