# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

def common_pods

	#UI
	pod 'SteviaLayout', '~> 4.7.3'

	# Reactive
	pod 'RxSwift', '~> 5.1.1'
    	pod 'RxCocoa', '~> 5.1.1'

	# Resources
    	pod 'R.swift', '~> 5.3.0'

end

target 'Repo' do
  use_frameworks!
	common_pods
end
